### ISSUE TITLE
3D 填充图 Mapbox 和 高德地图 统一高度

### ISSUE THREAD

**Issue by lzxue** [antvis/L7#2018]
### AntV Open Source Contribution Plan（可选）

- [ ] 我同意将这个 Issue 参与 OSCP 计划

### Issue 类型

高级任务

### 任务介绍

目前对于填充图，在Mapbox 和 高德地图下高度表现不一致。

https://l7.antv.antgroup.com/examples/polygon/3d/#polygon_stylemap
re #1634

**Comment by weilb** [comment]
I have the same problem , Mapbox Instance also has problems with the height of the line wall

**Comment by deletenothing** [comment]
deletenothing 认领

**Comment by zhuyyafd** [comment]
zhuyyafd 认领

**Comment by lzxue** [comment]
@deletenothing @weilb 感谢认领，这块问题是，shader 内部需要处理单位换算，有需要我可以讲解实现机制

**Comment by deletenothing** [comment]
请问可以微信联系吗

**Comment by deletenothing** [comment]
可以加微信交流一下吗

**Comment by deletenothing** [comment]
> @deletenothing @weilb 感谢认领，这块问题是，shader 内部需要处理单位换算，有需要我可以讲解实现机制

可以加微信交流一下吗？

**Comment by Pureblackkk** [comment]
Hi, there. I still found this problem with your new pr code added with Mapbox or TencentMap. I think the problem comes from the wall types vertex shader. In the wall vertex shader the aSize.x being used as the height of the wall, and it'll be converted to the real pixel height in the world coordinates corresponding to the current u_Zoom level when the height is not fixed. After several tries, I found when I fixed the height which will be passed to the fragment shader or invert the coordinates transformation with pow(2.0, u_Zoom - 1), it will be fine or at least not that wired. Though I didn't totally figure out the mechanism of how the coordinates system working in L7 and the difference of it in MapBox, I think it's the problem of zoom level transformation. Looking forward to hearing you suggestion @lzxue

**Comment by lzxue** [comment]
Are you talking about the Wall layer?  I haven't tested the wall layer yet and  The wall layer capability is not perfect yet.it still has promblem.

another question：

the case of non-fixed height, the unit is in meters, while for fixed height, it is measured in pixels. this is a design problem with using heightfixed. This is a historical issue. I have long wanted to refactor it. Using heightUnit is more appropriate. I will fix this in the future.

- You can think that the coordinate system of L7 is the same as mapbox, only the Amap map is special.

**Comment by Pureblackkk** [comment]
I see. What do you mean by height unit, is it kind of the dimensionless quantity which is used commonly for all kinds of coordinate system? Anyway, if you solve this issue I'll definitely glad to see how that works out, and also it's great if you could share more information and knowledge in the future. (Thumb up XD)
