### ISSUE TITLE
npm install时报错：Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by lizhongzhen11** [antvis/L7#37]
* **L7 Version**:
* **Platform**:
* **Mini Showcase(like screenshots)**:
* **CodePen Link**:

npm install时报错：Appears to be a git repo or submodule.

https://stackoverflow.com/questions/27356915/how-to-update-npm-modules-ignoring-a-git-repo/40891438

**Comment by dodumosu** [comment]
![1__dipoodumosu_Dipos-MacBook-Pro____work_projects_personal_devc-full-stack_web-maps__zsh__and_npm_install时报错：Appears_to_be_a_git_repo_or_submodule__·_Issue__37_·_antvis_L7_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/66879541-6b9c4300-efb6-11e9-9591-5ab466a08e84.png)
![1__dipoodumosu_Dipos-MacBook-Pro____work_projects_personal_devc-full-stack_web-maps__zsh__and_npm_install时报错：Appears_to_be_a_git_repo_or_submodule__·_Issue__37_·_antvis_L7_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/66879579-a56d4980-efb6-11e9-8e44-7ee56153e350.png)

have had the same problem since at least v1.3.5

**Comment by lzxue** [comment]
你自己项目的问题吧

**Comment by lizhongzhen11** [comment]
@lzxue 
不是哦，仔细看我给的stackoverflow链接，然后再看@antv/l7目录下面是不是有个.git目录？
我昨天下载的的确有，把这个.git目录删除即可

**Comment by lzxue** [comment]
已修复
